from fuzzywuzzy import fuzz
from process import Person
import sys
import os
import csv

# ------------------------------------------------------------------
# Constants
FIELD_NAMES = ['birth_date', 'expiry_date', 'gender', 'name',
               'surname', 'number', 'filename']

# ------------------------------------------------------------------
# Ovaj fajl ne menjati, da bi automatsko ocenjivanje bilo moguce
if len(sys.argv) > 1:
    VALIDATION_DATASET_PATH = sys.argv[1]
else:
    VALIDATION_DATASET_PATH = '.' + os.path.sep + 'dataset' + os.path.sep + 'validation' + os.path.sep
# ------------------------------------------------------------------

ground_truth = dict()

with open(VALIDATION_DATASET_PATH + 'annotations.csv') as file:
    reader = csv.DictReader(file)

    for row in reader:
        filename = row.pop('filename')
        person = Person(**row)
        ground_truth[filename] = person

# read results file generated by the main.py
results = dict()

with open('result.csv') as file:
    reader = csv.DictReader(file)
    for row in reader:
        filename = row.pop('filename')
        person = Person(**row)
        results[filename] = person

# evaluate how results file matches the labelled samples
total_samples = len(ground_truth)

authority_hits = 0
birth_date_hits = 0
birth_place_hits = 0
code_hits = 0
expiry_date_hits = 0
gender_hits = 0
issue_date_hits = 0
name_hits = 0
surname_hits = 0
nationality_hits = 0
number_hits = 0

coeff = {
    'birth_date': 0.2,
    'expiry_date': 0.2,
    'gender': 0.1,
    'name': 0.2,
    'surname': 0.2,
    'number': 0.2,
}

coeff_total = sum(coeff.values())
coeff_norm = {key: value / coeff_total for key, value in coeff.items()}

for file_name in results.keys():
    extracted_person: Person = results[file_name]
    truth_person: Person = ground_truth[file_name]

    birth_date_hits += (extracted_person.birth_date == truth_person.birth_date) * coeff_norm['birth_date']
    expiry_date_hits += (extracted_person.expiry_date == truth_person.expiry_date) * coeff_norm['expiry_date']
    gender_hits += (extracted_person.gender == truth_person.gender) * coeff_norm['gender']
    name_hits += (fuzz.ratio(truth_person.name, extracted_person.name) / 100) * coeff_norm['name']
    surname_hits += (fuzz.ratio(truth_person.surname, extracted_person.surname) / 100) * coeff_norm['surname']
    number_hits += (fuzz.ratio(truth_person.number, extracted_person.number) / 100) * coeff_norm['number']

total = sum([birth_date_hits, expiry_date_hits, gender_hits, name_hits, surname_hits, number_hits]) / total_samples

print(total * 100)
